### ISSUE TITLE
sst25vf_spi.h: No such file or directory

### ISSUE THREAD

**Issue by mwbrady** [m-mcgowan/spark-flashee-eeprom#18]
Veryfing code using this library in Particle Build fails with this error:
```
flashee-eeprom/flashee-eeprom-impl.h:1290:25: fatal error: sst25vf_spi.h: No such file or directory
 #include "sst25vf_spi.h"
                         ^
```

**Comment by jmohin** [comment]
Same for me, but only on Photon, still works fine for Core.

**Comment by m-mcgowan** [comment]
This library isn't presently supported on the photon. If you're seeing this error, then double-check in the web IDE that a Core is selected. (The error occurs only when the IDE compiles for the photon.)

**Comment by m-mcgowan** [comment]
Support for Photon and P1 now in master.

**Comment by shrm145** [comment]
I'm still getting this error with the Photon

**Comment by m-mcgowan** [comment]
@mwbrady, @jmohin  - can you guys confirm this issue is fixed for you\? Thanks!

**Comment by chadder** [comment]
I still get the error mentioned above when attempting to verify Photon code... :(

**Comment by m-mcgowan** [comment]
I'm so sorry about this! I thought I had published the Photon/P1 changes, but checking now, I had not! 1.8.0 now released to Particle Build.

**Comment by chadder** [comment]
@m-mcgowan - No worries. Compiles without error now; thanks!!

**Comment by m-mcgowan** [comment]
Thanks for confirming. :+1:

**Comment by jmohin** [comment]
I still see this error when I compile, probably because I haven't included it properly.  Using the latest particle firmware 0.4.7, and this import call:

#include "flashee-eeprom/flashee-eeprom.h"
using namespace Flashee;
